# Generated by Django 4.1.2 on 2022-12-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='designation',
        ),
    ]
