# Generated by Django 4.1.2 on 2022-11-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_image',
        ),
    ]
