# Generated by Django 4.1.2 on 2022-11-20 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_remove_post_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
