# Generated by Django 4.1.2 on 2022-11-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_image',
        ),
    ]
