# Generated by Django 4.1.2 on 2022-12-04 17:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[blog.models.validate_no_bad_words]),
        ),
    ]
