# Generated by Django 4.1.2 on 2023-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isprivate',
            field=models.BooleanField(default=False),
        ),
    ]
